---
- name: Pre-reqs for Elastic Search
  apt:
    name:
      - nginx
      - openjdk-11-jdk
    state: latest
    update_cache: yes

- name: Apt 
  apt:
    name: apt-transport-https
    state: present

- name: Apt Repository
  apt_repository:
    filename: elastic-7.x
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present

- name: Elastic Search Installation
  apt:
    name: elasticsearch
    state: present
    update_cache: no

- name: Network Host
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'

- name: Http Port
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port'
    line: 'http.port: 9200'

- name: Timeout
  lineinfile:
    dest: /etc/systemd/system/elasticsearch.service
    regexp: 'TimeoutStartSec = '
    line: 'TimeoutStartSec = 900'

- name: Discovery Type
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    line: 'discovery.type: "single-node"'

- name: Elastic Search Start
  service:
    name: elasticsearch
    state: started

- name: Kibana Installation
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: Server Host
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: 'server.host'
    line: 'server.port: 5601'

- name: Hosts
  lineinfile:
    dest: /etc/kibana/kibana.yml
    regexp: 'elasticsearch.hosts:'
    line: 'elasticsearch.hosts: ["https://localhost:9200"]'

- name: Kibana Start
  service:
    name: kibana
    state: started

- name: Logstash Installation
  apt:
    name: logstash
    state: latest
    update_cache: yes

- name: Logstash Start
  service:
    name: logstash
    state: started

# tasks file for roles/elasticstack1ins
