---
- name: Packages for Grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_7.3.6_amd64.deb
  register: pkg_grafana

- name: Dpkg Selections
  dpkg_selections:
    name: grafana_7.3.6_amd64.deb
    selection: install
  when: pkg_grafana.changed

- name: Libfontconfig Installation
  apt:
    name: libfontconfig1
    state: latest
    update_cache: yes

- name: Grafana Installation
  apt: 
    name: grafana
    state: latest
    update_cache: yes

- name: Grafana Start
  service:
    name: grafana-server
    state: started

- name: Prometheus Installation
  apt:
    name: prometheus
    state: latest
    update_cache: yes

- name: Influxdb Key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Influxdb Repo
  apt_repository:
    repo: 'deb https://repos.influxdata.com/ubuntu focal stable'
    state: present 

- name: Influxdb Installation
  apt:
    name: influxdb
    state: latest
    update_cache: yes

- name: Influxdb Start
  service:
    name: influxdb
    state: started
    update_cache: yes
# tasks file for roles/grafana1ins
