---
- name: Httpd Installation
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: Register Httpd Index
  copy:
    content: "Hi, I'm Vyanne"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: httpd

- name: Httpd Start
  service: 
    name: httpd
    state: started
  when: httpd.changed

- name: Firewall Stop
  service:
    name: firewalld
    state: stopped
    update_cached: yes

- name: Mariadb Installation
  yum:
    name: mariadb-server
    state: latest
    update_cache: yes

- name: Register MySQL Index
  copy:
    content: "Hi, I'm Vyanne"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql

- name: Mariadb Start
  service:
    name: mariadb
    state: started
  when: mysql.changed

- name: Php Installation
  yum:
    name:
      - php-mysqlnd
      - php
    state: latest
    update_cache: yes

- name: Register Php Index
  copy:
    content: "Hi, I'm Vyanne"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
  register: php

- name: Httpd Restart
  service:
    name: httpd
    state: restarted
  when: php.changed
# tasks file for roles/lamp2ins
