---
- name: Apache2 Installation
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: Register Apache Index
  copy:
    content: "Hi, I'm Vyanne"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql_index

- name: Apache2 Service Restart
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: apache_index.changed

- name: Ufw Apache2
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: MySQL Server Installation
  apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: Register MySQL Index
  copy:
    content: "Hi, I'm Vyanne"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql_index

- name: MySQL Service Start
  service:
    name: mysql
    state: restarted
    enabled: yes
  when: mysql_index.changed

- name: Php Installation
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: latest
    update_cache: yes

- name: Register Php Index
  copy:
    content: "Hi, I'm Vyanne"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
# tasks file for roles/lamp1ins
